version: '3.1'

services:
  dev_mtb_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'dev_mtb_db'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'root'
      # You can use whatever password you like
      POSTGRES_PASSWORD: 'root'
      # Password for root access
      POSTGRES_ROOT_PASSWORD: 'root'
    ports:
     - ${POSTGRES_PORT:-5432}:5432