version: '3.1'

services:
  mytb:
    depends_on:
      - mtb_db
    build:
      context: .
    environment:
      BOT_NAME=${BOT_NAME}
      BOT_TOKEN=${BOT_TOKEN}
      BOT_DB_USERNAME: ${BOT_DB_USERNAME}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
    restart: always
  mtb_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'mtb_db'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: ${BOT_DB_USERNAME}
      # You can use whatever password you like
      POSTGRES_PASSWORD: ${BOT_DB_PASSWORD}
      # Password for root access
      POSTGRES_ROOT_PASSWORD: 'root'
    ports:
      - ${POSTGRES_PORT:-5432}:5432